#!/bin/sh

cd /opt/paperless
mkdir -p media data consume

cp /opt/paperless/requirements.txt /opt/paperless/requirements.txt.orig
sed -i "" -e '/scikit-learn/d;/scipy/d;' /opt/paperless/requirements.txt

python3.9 -m venv --system-site-packages venv
. venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
cd src
python3 manage.py migrate

DJANGO_SUPERUSER_PASSWORD=admin python3 manage.py createsuperuser --noinput --email=root@localhost --username=admin
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/opt/paperless/data/nltk" snowball_data
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/opt/paperless/data/nltk" stopwords
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/opt/paperless/data/nltk" punkt
deactivate

